name: dkong_arcade
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.28.1
  # Flame audio needs to be properly initialized with actual sound files
  # For this demo we'll use a mock audio manager
  # flame_audio: ^2.11.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/barrel.png
    - assets/images/platform.png
    - assets/images/kong.png
    - assets/images/princess.png
    - assets/images/ladder.png
    - assets/images/heart.png
    - assets/images/
    - assets/audio/

